apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fleet-manager
  namespace: fleet-ops
  labels:
    app: fleet-manager
    phase: phase-1
spec:
  source:
    type: Git
    git:
      uri: https://github.com/RHPhysicalAI/industrial-ai-showcase.git
      ref: phase3
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: workloads/fleet-manager/container/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: fleet-manager:latest
  triggers:
    - type: ConfigChange
