apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  storageClassName: gp3
