apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mes-stub
  namespace: fleet-ops
  labels:
    app: mes-stub
    phase: phase-2
spec:
  source:
    type: Git
    git:
      uri: https://github.com/RHPhysicalAI/industrial-ai-showcase.git
      ref: phase3
    sourceSecret:
      name: git-source-secret
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: workloads/mes-stub/container/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: mes-stub:latest
  triggers:
    - type: ConfigChange
