apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: robot-edge
resources:
- openvla-server-imagestream.yaml
- openvla-server-buildconfig.yaml
- openvla-server-deployment.yaml
- openvla-server-service.yaml
