apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: robot-edge
resources:
- ../../base/vla-inference
patches:
- path: model-vla-warehouse-patch.yaml
  target:
    kind: InferenceService
    name: vla-warehouse
