apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
  name: vllm-runtime
  namespace: robot-edge
spec:
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8888
    serverType: ""
  containers:
  - args:
    - --model
    - /mnt/models
    - --port
    - "8080"
    - --served-model-name
    - $(MODEL_NAME)
    - --dtype
    - auto
    - --max-model-len
    - "4096"
    command:
    - python3
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: MODEL_NAME
      value: vla-warehouse
    image: vllm/vllm-openai:v0.6.3.post1
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: "4"
        memory: 16Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "2"
        memory: 8Gi
        nvidia.com/gpu: "1"
  grpcDataEndpoint: ""
  grpcEndpoint: ""
  protocolVersions:
  - v1
  - v2
  supportedModelFormats:
  - autoSelect: true
    name: vllm
    version: "1"
