apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: wms-stub
  namespace: fleet-ops
  labels:
    app: wms-stub
    phase: phase-1
spec:
  source:
    type: Git
    git:
      uri: https://github.com/RHPhysicalAI/industrial-ai-showcase.git
      ref: phase3
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: workloads/wms-stub/container/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: wms-stub:latest
  triggers:
    - type: ConfigChange
