apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: factory-b
resources:
- model-vla-warehouse-isvc.yaml
- policy-version.yaml
- mission-dispatcher-b-serviceaccount.yaml
- mission-dispatcher-b-imagestream.yaml
- mission-dispatcher-b-buildconfig.yaml
- mission-dispatcher-b-configmap.yaml
- mission-dispatcher-b-deployment.yaml
- mission-dispatcher-b-service.yaml
- openvla-server-imagestream.yaml
- openvla-server-buildconfig.yaml
- openvla-server-deployment.yaml
- openvla-server-service.yaml
