apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vla-warehouse
  namespace: factory-b
  annotations:
    serving.knative.dev/rollout-duration: "0"
spec:
  predictor:
    tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    model:
      modelFormat:
        name: vllm
      storageUri: hf://Qwen/Qwen2.5-7B-Instruct
      resources:
        limits:
          nvidia.com/gpu: '1'
          cpu: '4'
          memory: 16Gi
        requests:
          nvidia.com/gpu: '1'
          cpu: '2'
          memory: 8Gi
