apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-version
  namespace: factory-b
  labels:
    app.kubernetes.io/part-of: factory-b
    showcase.redhat.com/component: policy-version
data:
  version: vla-warehouse-v1.6
  model-uri: hf://openvla/openvla-7b
  promoted-at: '2026-07-24T15:30:43.735916+00:00'
