apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mission-dispatcher
  namespace: robot-edge
spec:
  source:
    git:
      uri: https://github.com/RHPhysicalAI/industrial-ai-showcase.git
      ref: main
